name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: build
        run: |
          poetry build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: "${{ secrets.TEST_PYPI_API_TOKEN }}"
          repository_url: "https://test.pypi.org/legacy/"
      - name: Create Release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ github.ref }}"
          release_name: "v${{ github.ref }}"
          draft: true
          prerelease: false
